# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a5de122221a3d77d428f285b7082c36a"
name = "Daisy London"
handle = "daisy-london"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
